version: '3.8'
services:
  web:
    build: .
    container_name: task-manager-backend
    env_file:
      - '.env'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database

  database:
    image: postgres:15-bullseye
    container_name: task-manager-database
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 3s
      retries: 3
